server:
  port: ${SERVER_PORT:8091}
blog:
  service:
    url: ${BLOG_SERVICE_URL:http://localhost:8090}
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: userService
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user}
    username: ${DB_USERNAME:kabi}
    password: ${DB_PASSWORD:kabil@007}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: com.bamboo.userService.common.helper.CustomHibernateJsonFormatter
